---

- name: Get current sesi dir
  ansible.builtin.command:
    cmd: ls -l {{ houdini_license_server_dir }}
  changed_when: false
  register: sesi_dir_output

- name: Show sesi dir content
  ansible.builtin.debug:
    var: sesi_dir_output

# TODO verify via sesictrl print-license instead
- name: Check for existing local houdini licenses
  ansible.builtin.stat:
    path: "{{ houdini_license_server_dir }}/licenses"
  register: h_licenses_file

- name: Set up apprentice license
  when: not h_licenses_file.stat.exists
  block:
    - name: Get houdini license server code
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          sesictrl diagnostic | awk -F': *' '/Local server code/ {print $2}'
        chdir: "{{ houdini_license_server_dir }}"
        executable: "/bin/bash"
      changed_when: false
      register: license_server_result

    - name: Create venv for houdini license script
      ansible.builtin.pip:
        name:
          - pip
          - click
          - requests
        state: present
        virtualenv: "{{ houdini_download_script_venv_path }}"
        virtualenv_command: "python3 -m venv"
      delegate_to: localhost

    - name: "Get apprentice license key"
      ansible.builtin.command:
        cmd: >
          {{ houdini_download_script_venv_path }}/bin/python api_download.py get-non-commercial-license-key
          {{ sidefx_client_id }}
          {{ sidefx_client_secret_key }}
          {{ ansible_facts.fqdn }}
          {{ license_server_result.stdout }}
          {{ houdini_version }}
          "HOUDINI-NC;RENDER-NC"
        chdir: "{{ role_path }}/files"
      changed_when: false
      register: h_license_result
      delegate_to: localhost

    - name: Install apprentice licenses
      become: true
      loop: "{{ h_license_result.stdout | from_json }}"
      ansible.builtin.shell:
        cmd: |
          sesictrl install --license-info {{ item }}
        chdir: "{{ houdini_license_server_dir }}"
        executable: "/bin/bash"
        creates: "{{ houdini_license_server_dir }}/licenses"
      register: license_result
      changed_when: license_result.rc == 0

    - name: Restart sesinetd
      become: true
      when: license_result.changed # noqa no-handler
      ansible.builtin.systemd:
        name: sesinetd
        state: restarted

...
