---

- name: Set package
  ansible.builtin.set_fact:
    houdini_package: "{{ houdini_package_path.houdini_package }}"

- name: Ensure sidefx packages (online)
  when: houdini_iso_url == ""
  block:
    - name: Write settings file
      become: true
      ansible.builtin.copy:
        dest: "{{ houdini_package_dir }}/houdini_settings"
        content: |
          client_id={{ sidefx_client_id }}
          client_secret={{ sidefx_client_secret_key }}
          accept_eula=SideFX-{{ eula_date }}
        owner: root
        group: root
        mode: "0644"
      no_log: true

    - name: Install sidefx labs (online)
      become: true
      # eula ref: https://www.sidefx.com/download/eula/
      when: houdini_iso_url == ""
      ansible.builtin.command:
        cmd: >-
          ./houdini_installer install-package
          --package-name '{{ houdini_package.name }} {{ houdini_package.version }} {{ houdini_package.build }}'
          --settings-file {{ houdini_package_dir }}/houdini_settings
          --installdir {{ houdini_sidefx_packages_path }}
        chdir: "{{ houdini_launcher_dir }}/bin"
        creates: '{{ houdini_sidefx_packages_path }}/{{ houdini_package.name | regex_replace("\s", "") }}{{ houdini_package.version }}/LICENSE.md'

- name: Install sidefxlabs (offline)
  become: true
  # eula ref: https://www.sidefx.com/download/eula/
  when: houdini_iso_url != ""
  ansible.builtin.command:
    cmd: >-
      ./houdini_installer install-package
      --package-name '{{ houdini_package.name | regex_replace("\s", "") }}{{ houdini_package.version }}.{{ houdini_package.build_number }}'
      --offline-installer {{ houdini_package_dir }}/{{ houdini_iso_url | basename }}
      --installdir {{ houdini_sidefx_packages_path }}
    chdir: "{{ houdini_launcher_dir }}/bin"
    creates: '{{ houdini_sidefx_packages_path }}/{{ houdini_package.name | regex_replace("\s", "") }}{{ houdini_package.version }}/LICENSE.md'

...
