---

- name: Install selinux mod dependencies
  become: true
  loop: "{{ selinux_packages }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Create temp directory
  become: true
  ansible.builtin.file:
    path: /tmp/sesinetd_policy
    state: directory
    mode: "0755"

- name: Copy policy sources
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/sesinetd_policy/{{ item }}"
    mode: '0644'
  loop:
    - sesinetd.te
    - sesinetd.fc
    - sesinetd.if

- name: Build SELinux policy with make
  become: true
  community.general.make:
    chdir: "/tmp/sesinetd_policy"
    file: /usr/share/selinux/devel/Makefile
    target: all

- name: Install policy module
  become: true
  ansible.builtin.command:
    cmd: semodule -i /tmp/sesinetd_policy/sesinetd.pp
  register: semodule_result
  changed_when: semodule_result.rc == 0

- name: Assign TCP port 1715 to sesinetd_port_t
  become: true
  community.general.seport:
    ports: 1715
    proto: tcp
    setype: sesinetd_port_t
    state: present

- name: Assign TCP port 1714 to hserver_port_t
  become: true
  community.general.seport:
    ports: 1714
    proto: tcp
    setype: hserver_port_t
    state: present

- name: Apply file contexts
  ansible.builtin.command:
    cmd: restorecon -Rv /usr/lib/sesi/
  register: restorecon_result
  changed_when: "'Relabeled' in restorecon_result.stdout"

...
