---

- name: Check for existing houdini license service
  ansible.builtin.stat:
    path: "{{ houdini_license_server_dir }}/sesinetd"
  register: sesinetd_file

- name: "Online install for License Server"
  when: houdini_iso_url == "" and not sesinetd_file.stat.exists
  block:
    - name: Write settings file
      become: true
      ansible.builtin.copy:
        dest: "{{ houdini_package_dir }}/houdini_settings"
        content: |
          client_id={{ sidefx_client_id }}
          client_secret={{ sidefx_client_secret_key }}
          accept_eula=SideFX-{{ eula_date }}
        owner: root
        group: root
        mode: "0644"
      no_log: true

    - name: "Online install for License Server"
      become: true
      # eula ref: https://www.sidefx.com/download/eula/
      ansible.builtin.command:
        cmd: >-
          ./houdini_installer install
          --product "License Server"
          --accept-EULA 'SideFX-{{ eula_date }}'
          --version {{ houdini_version }}.{{ houdini_build_number }}
          --settings-file {{ houdini_package_dir }}/houdini_settings
        chdir: "{{ houdini_launcher_dir }}/bin"
        creates: "{{ houdini_install_dir }}/licenses.disabled"

- name: Install license service (offline)
  become: true
  # eula ref: https://www.sidefx.com/download/eula/
  when: houdini_iso_url != "" and not sesinetd_file.stat.exists
  ansible.builtin.command:
    cmd: >-
      ./houdini_installer install
      --product "License Server"
      --accept-EULA SideFX-{{ eula_date }}
      --offline-installer {{ houdini_package_dir }}/{{ houdini_iso_url | basename }}
    chdir: "{{ houdini_launcher_dir }}/bin"
    creates: "{{ houdini_license_server_dir }}/licenses.disabled"

- name: Start sesinetd service
  become: true
  ansible.builtin.systemd_service:
    name: sesinetd.service
    enabled: true
    state: started
    daemon_reload: true

- name: Get service facts
  become: true
  ansible.builtin.service_facts:

- name: Test if the license service is running
  ansible.builtin.assert:
    that:
      - ansible_facts.services['sesinetd.service'].state == "running"
    quiet: true

- name: Disable hserver in container
  become: true
  when: ansible_facts.virtualization_type in ["docker", "podman", "lxc", "containerd", "container"]
  ansible.builtin.systemd:
    name: hserver
    state: stopped
    enabled: false

...
