---

- name: Check for credentials
  ansible.builtin.assert:
    that:
      - sidefx_client_id is defined
      - sidefx_client_secret_key is defined
    fail_msg: "Houdini download api credentials not defined"
    quiet: true

- name: Verify houdini version
  when: houdini_iso_url != ""
  ansible.builtin.assert:
    that:
      - "houdini_version ~ '.' ~ houdini_build_number ~ '-linux_x86_64' in houdini_iso_url"
    fail_msg: |
      Failed to find requested version '{{ houdini_version }}.{{ houdini_build_number }}-linux_x86_64' in {{ houdini_iso_url }}.

      Is this the intended source?
    quiet: true

- name: Filter products by feature list
  ansible.builtin.set_fact:
    enabled_houdini_products: >-
      {{
        houdini_products
        | dict2items
        | selectattr('key', 'in', houdini_features)
        | items2dict
      }}

- name: Check for existing houdini products
  become: true
  loop: "{{ enabled_houdini_products | dict2items }}"
  loop_control:
    loop_var: product
    label: "{{ product.key }}"
  ansible.builtin.stat:
    path: "{{ product.value.install_path }}"
  register: product_install_paths

- name: Check for existing houdini package
  loop: "{{ houdini_packages }}"
  loop_control:
    loop_var: "houdini_package"
    label: "{{ houdini_package.name }}"
  ansible.builtin.stat:
    path: '{{ houdini_sidefx_packages_path }}/{{ houdini_package.name | regex_replace("\s", "") }}{{ houdini_package.version }}/LICENSE.md'
  register: package_install_path

- name: Remap product install paths to simple dict
  ansible.builtin.set_fact:
    products_query: >-
      {{
        dict(
          product_install_paths.results
          | map(attribute='product.key')
          | zip(product_install_paths.results | map(attribute='stat.exists'))
        )
      }}

- name: Get houdini artifacts
  ansible.builtin.include_tasks:
    file: get_artifacts.yml

- name: Install houdini launcher
  become: true
  when: not launcher_installation_path.stat.exists
  ansible.builtin.command:
    cmd: "./{{ launcher_filename }} --no-desktop-menus {{ houdini_launcher_dir }}"
    chdir: "{{ houdini_package_dir }}"
    creates: "{{ houdini_launcher_dir }}/uninstall_houdini_launcher.sh"

- name: Install houdini products
  loop: "{{ product_install_paths.results }}"
  loop_control:
    loop_var: houdini_product
    label: "{{ houdini_product.product.key }}"
  when: not houdini_product.stat.exists
  ansible.builtin.include_tasks:
    file: install_products.yml

- name: Include sidefx packages
  loop: "{{ package_install_path.results }}"
  loop_control:
    loop_var: "houdini_package_path"
    label: "{{ houdini_package_path.houdini_package.name }}"
  when: houdini_packages and not houdini_package_path.stat.exists
  ansible.builtin.include_tasks:
    file: install_houdini_packages.yml

- name: Install houdini dependencies
  become: true
  ansible.builtin.package:
    name: "{{ houdini_dependencies[houdini_version][ansible_facts.os_family | lower] | difference(['epel-release'] if ansible_facts.distribution | lower == 'fedora' else []) }}"
    state: present
    update_cache: true

- name: Ensure selinux policy
  when: houdini_license_service and ansible_facts.selinux.status == "enabled"
  block:
    - name: Check installed module version
      become: true
      ansible.builtin.command:
        cmd: semodule -l
      register: semodule_list
      changed_when: false

    - name: Include selinux policy
      when: "'sesinetd' not in semodule_list.stdout_lines"
      ansible.builtin.include_tasks:
        file: license_service_selinux.yml

- name: Include local license service
  when: houdini_license_service
  ansible.builtin.include_tasks:
    file: local_license_service.yml

- name: Inlcude apprentice license
  when: houdini_apprentice_license
  ansible.builtin.include_tasks:
    file: apprentice_license.yml

- name: Configure houdini
  when: houdini_include_user_config
  ansible.builtin.include_tasks:
    file: user_config.yml

- name: Cleanup remote
  become: true
  ansible.builtin.file:
    path:
      - "{{ license_selinux_module_tmp_dir }}"
      - "{{ houdini_package_dir }}"
    state: absent

- name: Cleanup controller venv
  ansible.builtin.file:
    path: "{{ houdini_download_script_venv_path }}"
    state: absent
  delegate_to: localhost

...
