---

- name: Install pip dependency
  become: true
  ansible.builtin.package:
    name: python3-packaging
    state: "present"

- name: Install python venv
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: "{{ venv_package[ansible_distribution] }}"
    state: "present"
    update_cache: true

- name: Create venv
  ansible.builtin.command:
    cmd: "python3 -m venv {{ download_script_venv_path }}"
    creates: "{{ download_script_venv_path }}/bin/activate"

- name: Create venv for Houdini install script
  ansible.builtin.pip:
    name:
      - pip
      - click
      - requests
    state: present
    virtualenv: "{{ download_script_venv_path }}"
    virtualenv_command: "python3 -m venv"

- name: Ensure temporary install dir exists
  become: true
  ansible.builtin.file:
    path: "{{ houdini_package_dir }}"
    state: "directory"
    mode: "0755"
    owner: "root"
    group: "root"

- name: Copy sidefx download api script
  become: true
  loop:
    - "sidefx.py"
    - "api_download.py"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ houdini_package_dir }}/{{ item }}"
    mode: "0755"
    owner: "root"
    group: "root"

- name: "Query package for version {{ houdini_version ~ '.' ~ houdini_build_number }}"
  ansible.builtin.command:
    cmd: >
      {{ download_script_venv_path }}/bin/python api_download.py get-package-name
      {{ sidefx_client_id }}
      {{ sidefx_client_secret_key }}
      {{ houdini_version }}
      True
    chdir: "{{ houdini_package_dir }}"
  changed_when: false
  register: h_package_result

- name: "Run download script for version {{ houdini_version ~ '.' ~ houdini_build_number }}"
  become: true
  ansible.builtin.command:
    cmd: >
      {{ download_script_venv_path }}/bin/python api_download.py get-setup
      {{ sidefx_client_id }}
      {{ sidefx_client_secret_key }}
      {{ houdini_version }}
      {{ houdini_build_number }}
      {{ houdini_package_dir }}
    chdir: "{{ houdini_package_dir }}"
    creates: "{{ houdini_package_dir }}/{{ h_package_result.stdout }}"

...
