---

- name: Get python version
  ansible.builtin.command:
    cmd: python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
  changed_when: false
  register: python_version

- name: Create venv
  ansible.builtin.command:
    cmd: "python3 -m venv {{ download_script_venv_path }}"
    creates: "{{ download_script_venv_path }}/bin/activate"

- name: Install pip module dependency
  ansible.builtin.command:
    cmd: "{{ download_script_venv_path }}/bin/python -m pip install packaging"
    creates: "{{ download_script_venv_path }}/lib/python{{ python_version.stdout }}/site-packages/packaging"

- name: Create venv for Houdini install script
  ansible.builtin.pip:
    name:
      - pip
      - click
      - requests
    state: present
    virtualenv: "{{ download_script_venv_path }}"
    virtualenv_command: "python3 -m venv"

- name: Ensure temporary install dir exists
  become: true
  ansible.builtin.file:
    path: "{{ houdini_package_dir }}"
    state: "directory"
    mode: "0755"
    owner: "root"
    group: "root"

- name: Copy sidefx download api script
  become: true
  loop:
    - "sidefx.py"
    - "api_download.py"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ houdini_package_dir }}/{{ item }}"
    mode: "0755"
    owner: "root"
    group: "root"

- name: "Query package for version {{ houdin_version ~ '.' ~ houdini_build_number }}"
  ansible.builtin.command:
    cmd: >
      {{ download_script_venv_path }}/bin/python api_download.py get-package-name
      {{ sidefx_client_id }}
      {{ sidefx_client_secret_key }}
      {{ houdin_version }}
      True
    chdir: "{{ role_path }}/files"
  changed_when: false
  register: h_package_result

- name: "Run download script for version {{ houdin_version ~ '.' ~ houdini_build_number }}"
  become: true
  ansible.builtin.command:
    cmd: >
      {{ download_script_venv_path }}/bin/python api_download.py get-setup
      {{ sidefx_client_id }}
      {{ sidefx_client_secret_key }}
      {{ houdin_version }}
      {{ houdini_build_number }}
      {{ houdini_package_dir }}
    chdir: "{{ houdini_package_dir }}"
    creates: "{{ houdini_package_dir }}/{{ h_package_result.stdout }}"

- name: Cleanup installer venv on remote host
  become: true
  ansible.builtin.file:
    path: "{{ download_script_venv_path }}"
    state: absent

...
