---

- name: Add hqueue-server directory
  when: '"hqueue-server" in houdini_features'
  ansible.builtin.set_fact:
    houdini_flags: "{{ houdini_flags }} --hqueue-server-dir {{ hqueue_server_dir }}"

- name: Add hqueue-client directory
  when: '"hqueue-client" in houdini_features'
  ansible.builtin.set_fact:
    houdini_flags: "{{ houdini_flags }} --hqueue-client-user {{ hqueue_client_user }} --hqueue-client-dir {{ hqueue_client_dir }}"

- name: Display houdini install flags
  ansible.builtin.debug:
    msg: |
      ./houdini.install
      --accept-EULA {{ eula_date }}
      --install-houdini
      --install-bin-symlink
      --install-hfs-symlink
      {{ houdini_flags }}
      --auto-install
      --make-dir {{ houdin_install_dir }}
      {{ houdin_install_dir }}

- name: Install houdini
  become: true
  ansible.builtin.command:
    cmd: >-
      ./houdini.install
      --accept-EULA {{ eula_date }}
      --install-houdini
      --install-bin-symlink
      --install-hfs-symlink
      {{ houdini_flags }}
      --auto-install
      --make-dir {{ houdin_install_dir }}
      {{ houdin_install_dir }}
  args:
    chdir: "{{ houdini_package_dir }}/{{ installer_extracted }}"
    creates: "{{ houdin_install_dir }}/houdini.uninstall"

- name: Cleanup installer directory
  become: true
  ansible.builtin.file:
    path: "{{ houdini_package_dir }}/{{ installer_extracted }}"
    state: absent

...
