---

- name: Test houdini
  ansible.builtin.command:
    cmd: houdini --version
  changed_when: false

- name: Get houdini uninstaller
  ansible.builtin.stat:
    path: "{{ houdini_install_dir }}/houdini.uninstall"
  register: houdini_installation_path

- name: Test houdini install path
  ansible.builtin.assert:
    that:
      - houdini_installation_path.stat.exists
    fail_msg: "Failed to find houdini install directory {{ houdini_install_dir }}"
    quiet: true

- name: Check license manager
  when: '"license" in houdini_features'
  block:
    - name: Get license manager service status
      ansible.builtin.command:
        cmd: "systemctl is-active sesinetd"
      changed_when: false
      register: sesinetd_status

    - name: Test sesinetd service state
      ansible.builtin.assert:
        that:
          - sesinetd_status.stdout == "active"
        fail_msg: "Expected state active for service 'sesinetd.service', got: {{ sesinetd_status.stdout }}"
        quiet: true

    - name: Check SELinux module
      when: ansible_os_family == "RedHat"
      block:
        - name: Get selinux module
          become: true
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              semodule -l | grep sesinetd
            executable: /bin/bash
          changed_when: false
          register: selinux_module_result

    - name: Test selinux module
      when: ansible_os_family == "RedHat"
      ansible.builtin.assert:
        that:
          - selinux_module_result.stdout == "sesinetd"
        fail_msg: "Failed to find selinux module for 'sesinetd'"
        quiet: true

...
