---

- name: Test houdini
  ansible.builtin.command:
    cmd: ./houdini --version
    chdir: "{{ houdini_install_dir }}/bin"
  changed_when: false

# TODO fix license installation
# https://www.sidefx.com/faq/question/why-do-i-see-the-message-license-is-not-useable-with-current-dns-settings/
# - name: Run hython
#   ansible.builtin.command:
#     cmd: ./hython -c "print('hello world')"
#     chdir: "{{ houdini_install_dir }}/bin"
#   register: hython_output
#   changed_when: false

# - name: Test hython output
#   ansible.builtin.assert:
#     that:
#       - hython_output.stdout == "hello world"
#     fail_msg: "Failed to fetch expected hython command output, got '{{ hython_output.stdout }}' instead"
#     quiet: true

...
