---

state: present

sidefx_client_id: "{{ lookup('ansible.builtin.env', 'SIDEFX_CLIENT_ID', default=undef()) }}"
sidefx_client_secret_key: "{{ lookup('ansible.builtin.env', 'SIDEFX_CLIENT_SECRET_KEY', default=undef()) }}"
houdini_version: "21.0"
houdini_build_number: "700"
houdini_production_only: true
houdini_iso_url: ""
houdini_launcher_url: ""
launcher_installer_file: install_houdini_launcher.sh
houdini_package_dir: "/tmp/houdini_package"
houdini_install_dir: "/opt/hfs{{ houdini_version }}.{{ houdini_build_number }}"
houdini_launcher_dir: "/opt/sidefx/launcher"
houdini_shfs_dir: "/opt/sidefx/sidefx_packages"
houdini_license_server_dir: "/usr/lib/sesi"

houdini_download_script_venv_path: "/tmp/houdini_download_venv"
houdini_features:
  - "Houdini"
  - "Engine Maya"
  - "Engine Unreal"
  - "Engine Unity"
  - "HQueue Server"
  - "HQueue Client"
houdini_products:
  Houdini:
    install_path: "{{ houdini_install_dir }}"
  Engine Maya:
    install_path: "/opt/sidefx/houdini_engine/Maya/{{ houdini_version }}.{{ houdini_build_number }}"
    install_flags: "--for-houdini {{ houdini_version }}.{{ houdini_build_number }}"
  Engine Unreal:
    install_path: "/opt/sidefx/houdini_engine/Unreal/{{ houdini_version }}.{{ houdini_build_number }}"
  Engine Unity:
    install_path: "/opt/sidefx/houdini_engine/Unity/{{ houdini_version }}.{{ houdini_build_number }}"
  HQueue Server:
    install_path: "/opt/hqueue"
  HQueue Client:
    install_path: "/home/hquser/hqclient"

eula_date: "2021-10-13"

houdini_packages:
  - name: "SideFX Labs"
    version: "{{ houdini_version }}"
    build: "Production Build"
    build_number: "{{ houdini_build_number }}"

license_selinux_module_tmp_dir: "/tmp/sesinetd-selinux"
houdini_license_service: true
houdini_apprentice_license: false
houdini_sidefx_packages_path: "/opt/sidefx/sidefx_packages"

houdini_include_user_config: true
houdini_user_config: "/etc/skel/houdini{{ houdini_version }}"
houdini_env:
  HOUDINI_NO_SPLASH: 1
  HOUDINI_SPLASH_MESSAGE: "configured by ansible"
houdini_vp_background_settings:
  BackgroundColor:
    rgb: "0.20 0.01 0.25"
    comment: "background color - adjusted"
  BackgroundBottomColor:
    rgb: "0.04 0.18 0.23"
    comment: "background color at bottom of view - adjusted"

venv_package:
  Debian: "python3-venv"
  Ubuntu: "python3.10-venv"

...
